version: "3.8"
networks:
  api_private_network:
    driver: bridge
    name: backend_network
  web_public_network:
    driver: bridge
    name: frontend_network
services:
  api:
    build:
      context: ./backend
    container_name: api-dojo-belt2
    depends_on:
      - postgresdb
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
    networks:
      api_private_network:
        aliases:
          - database_network
      web_public_network:
        aliases:
          - webapp
  postgresdb:
    container_name: postgresdb-dojo-belt2
    environment:
      - POSTGRES_USER=dojo_user
      - POSTGRES_DB=courses_db
      - POSTGRES_PASSWORD=post_belt2
    image: "postgres:11.2-alpine"
    networks:
      - api_private_network
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "db_vol:/var/lib/postgresql/data"
      - "db_config_vol:/etc/postgresql"
      - "./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
  web:
    build: ./frontend
    container_name: web-dojo-belt2
    depends_on:
      - api
    environment:
      API_URL: ${API_URL}
    networks:
      - web_public_network
    ports:
      - "80:3000"
volumes:
  db_config_vol:
  db_vol:
